apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base/namespaces/namespaces.yaml
- ../../base/deployments/nginx-deployment.yaml
- ../../base/services/nginx-service.yaml
- ../../base/configmaps/nginx-config.yaml
- nginx-ingress.yaml

patchesStrategicMerge:
- nginx-deployment-patch.yaml

configMapGenerator:
- name: nginx-config
  behavior: merge
  literals:
  - ENV=development
